spring:
  application:
    name: kotlin-study

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: on
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.deliwind: debug